### ISSUE TITLE
Swagger file definition support

### ISSUE THREAD

**Issue by openfly** [symphonyoss/python-symphony#49]
now that https://github.com/symphonyoss/symphony-api-spec exists, time to convert the language bindings to intake swagger definitions and write methods to classes based on that.

**Comment by openfly** [comment]
investigating legality of using yelp's bravado module for codegen.
may need to update bravado to add support for PKCS authentication.
investigating fixes to how we interact with urllib3 for direct passing of certs rather than writing to disk.
investigating more secure handling of p12 cert bundle once extracted.

**Comment by greenpau** [comment]
>  investigating fixes to how we interact with urllib3 for direct passing of certs rather than writing to disk.

@openfly , check this code snippet out:

```
import contextlib
import OpenSSL.crypto
import os
import requests
import ssl
import tempfile

@contextlib.contextmanager
def pfx_to_pem(pfx_path, pfx_password):
    ''' Decrypts the .pfx file to be used with requests. '''
    with tempfile.NamedTemporaryFile(suffix='.pem') as t_pem:
        f_pem = open(t_pem.name, 'wb')
        pfx = open(pfx_path, 'rb').read()
        p12 = OpenSSL.crypto.load_pkcs12(pfx, pfx_password)
        f_pem.write(OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, p12.get_privatekey()))
        f_pem.write(OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, p12.get_certificate()))
        ca = p12.get_ca_certificates()
        if ca is not None:
            for cert in ca:
                f_pem.write(OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cert))
        f_pem.close()
        yield t_pem.name

# HOW TO USE:
# with pfx_to_pem('foo.pem', 'bar') as cert:
#     requests.post(url, cert=cert, data=payload)
```

taken from https://gist.github.com/erikbern/756b1d8df2d1487497d29b90e81f8068

**Comment by openfly** [comment]
Yeah I hate the decorator approach.. I think I'll avoid tackling the PKCS auth components in the first run. 

branch codegen and new project python-symphony-binding are now filling out with the initial bits to gain parity using spec files for existing pod / agent spec files.

we'll keep using the auth components as is for now and tackle that later.

making progress here... should be approaching a PR soon.

**Comment by openfly** [comment]
This is now in 0.2.1 packages and beyond.
