### ISSUE TITLE
hello_world.py configuration file

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#51]
The following code https://github.com/symphonyoss/python-symphony/blob/master/examples/hello_world.py references `/etc/es-bot/es-bot.cfg`. It would be nice to have it together with the example.

It could save some time understanding https://github.com/symphonyoss/python-symphony/blob/master/symphony/Config/__init__.py

**Comment by greenpau** [comment]
Sample configuration file is in README.md of https://github.com/symphonyoss/metronome

**Comment by vivekpatani** [comment]
Keep getting this error saying

`No section: 'symphony``

What am I doing incorrectly? Please help.

**Comment by openfly** [comment]
I think I included an example config file.

At dinner ATM. Will check when I have a system in front of me again.

-Matt

**Comment by openfly** [comment]
Okay first off what version of the python-symphony module are you using?

I see some issues in the new python-symphony-binding module with python
3.5.2

I spun up a version of that to test.  Looks like how I am loading the yaml
swagger definitions doesn't translate well between python2 and python3.

So I'll try to push a fix for that.

Also a few print statements need some review... dunno how they got in there.

**Comment by greenpau** [comment]
> Okay first off what version of the python-symphony module are you using?

@openfly , 2.7.13

**Comment by openfly** [comment]
uhm that's not a version of the python-symphony module.  latest is 0.2.0 in
pip

latest in git is 0.2.1

**Comment by openfly** [comment]
fyi i have PRs open on both the binding and symphony projects.  I merged
all the python3 fixes for python-symphony and will cut a new release to pip
shortly.

however the base binding layer has a non-trivial issue with packaging the
data files from setup.py.  Basically i have 2 edited swagger spec files for
agent / pod endpoints.  But when I deploy em via setuptools ... they end up
in different pathes depending on if it's deployed to a virtualenv or to a
global path.  it may also do the same for python3.

I need to figure out a generic way to distribute those swagger spec files
with the module that doesn't break based on virtual env deployment vs
global.

-Matt

**Comment by greenpau** [comment]
> uhm that's not a version of the python-symphony module. latest is 0.2.0 in

@openfly , my bad. The version I used was the latest available Jun 14, 2017.

**Comment by openfly** [comment]
Okay yeah... that's pre-symphony-binding.

**Comment by openfly** [comment]
Okay

I pushed updates to python-symphony and python-symphony-binding

latest releases tested on 3.5... BUT i haven't solved the yaml thing yet
so if you run an install in a virtualenv you might need to copy the yaml
files from /path/to/venv/config/ to the egg / site_package for
python_symphony_binding
You will see an error about a missing yaml trying to run the hello_world.py

Just copy the file to that path ( 2 of em ).

Should work then.

Working on a solution for that bit now.

-Matt

**Comment by vivekpatani** [comment]
Hello @openfly, does this problem relate to the configuration file issue? I currently have satisfied all library requirements but fail to read config correctly.

https://github.com/symphonyoss/python-symphony/issues/65

Have included the logs here. Please let me know if you need more debug data. Will be happy to provide.

**Comment by openfly** [comment]
I see no issue with the config file in hello_world.py when running in
python 3.5.2.

Please ensure you have [symphony] at the top of your config file.

-Matt

**Comment by vivekpatani** [comment]
Does it matter that I'm running this on Windows? @openfly

**Comment by openfly** [comment]
It shouldn't but, I honestly do no testing for windows.

I do know someone has ran older versions of python-symphony on windows..
they contributed some bugs / proposed fixes.   Pre 0.2 release versions of
python-symphony SHOULD work.

I have not tested 0.2.0 releases on windows at all.  I have no idea what
would or would not break.

I have no testing environment for that.  I'd be glad to have folks open
issues on github for me to fix but I will need them scoped with enough data
to action them.  I rely on folks like you, Vivek, to let me know if there's
an issue.  If someone wants to assist in setting up some way to CICD test
windows... I'd appreciate it.  But it's outside my current scope of work,
and frankly, my time is pretty much spoken for.

-Matt

**Comment by vivekpatani** [comment]
I can help. I would more than happy to contribute. I've actually contributed a little to symphony before (not this project). I currently do not understand the issue at hand at all. I would still try to look for any solutions. Any hints on what could be wrong would be helpful. If I find it, I sure will patch and PR.

**Comment by openfly** [comment]
can you post a copy of your config file with the cert password redacted (
SERIOUS SECURITY RISK )?
and stream_id redacted as well.  less of a security risk but a minor
enumeration risk.

honestly you know redact anything you feel uncomfortable sharing.  I am
most concerned about basic file structure ( and uri structure somewhat ).

**Comment by vivekpatani** [comment]
Found the bug.

```[symphony]
symphony_pod_uri: https://company.symphony.com/
symphony_keymanager_uri: https://company-dev.symphony.com:8444/
symphony_agent_uri: https://company-dev.symphony.com:8444/
symphony_sessionauth_uri: https://company-dev-api.symphony.com:8444/
symphony_p12: P:\abcd\pycharm\python-symphony\examples\etc\es-bot\certs\bot.user100.p12
symphony_pwd: password
symphony_sid: example_gLc8hdZBHut6CUJnwMmzH3___qcqBgDKdA
```

Symphony P_12 needs to have the absolute path. Giving a relative path, it does not realise the location. I thought this was handled by os.dir automatically depending upon the OS. Now I'm running into new problems but that's my API.

Thank you. How do I make a fix for this?

**Comment by openfly** [comment]
Either PR directly against the project:

git fork the project to your own github account.
make changes.  merge em to your fork.

then open a PR against the symphonyoss project from your fork.

I can merge.

Or Just tell me the fix and I'll add it and put your name in the git commit
giving you credit there ( i dunno how to do that better ).

-Matt

**Comment by vivekpatani** [comment]
```-> P:\abcd\pycharm\python-symphony\examples\hello_world.py(20)main()
-> agent, pod, symphony_sid = conn.connect()

(Pdb) n
https://company-dev.symphony.com:8444/
<urlopen error [WinError 3] The system cannot find the path specified: 'P:\\Users\\abcd\\AppData\\Roaming\\python\\3.5.2\\lib\\site-packages\\config\\agent-api-public-deprecated.yaml'>
local variable 'agent' referenced before assignment
<urlopen error [WinError 3] The system cannot find the path specified: 'P:\\Users\\abcd\\AppData\\Roaming\\python\\3.5.2\\lib\\site-packages\\config\\pod-api-public-deprecated.yaml'>
local variable 'pod' referenced before assignment
```

Here is the stack trace. I've used Python Debugger.

Turns out the bug isn't fixed. sorry.

**Comment by openfly** [comment]
Yeah working on that bug now.

Just do a local filesystem search for : pod-api-public-deprecated.yaml

you should see a couple yaml files in that directory. Copy them all to
C:\\Users\\abcd\\AppData\\Roaming\\python\\3.5.2\\lib\\site-packages\\config\\

You may need to create that config directory to do so.

Should resolve it.

**Comment by openfly** [comment]
Honestly I am not sure how to approach this issue.  It appears setuptools
is not good at handling data_files assets in any idempotent way.

**Comment by openfly** [comment]
I just pushed a new symphony binding release version 0.0.9 of
python-symphony-binding.

this should resolve the bug.

**Comment by vivekpatani** [comment]
Yes, it did. Thank you.

On to the next issue though. The token returns fine but the keymanager errors out - the JSON is failing to parse the response. It is failing because the JSON is empty. Any specific reasons why that would happen?
