### ISSUE TITLE
SSL Exception handling

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#54]
The `connect()` will continue to `/keyauth/v1/authenticate` after `/sessionauth/v1/authenticate`, although the `/sessionauth/v1/authenticate` request failed with the following error:

```
Header value ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",) must be of type str or bytes, not <class 'requests.exceptions.SSLError'>
```

**Comment by greenpau** [comment]
The following function always returns `symphony.Auth.Auth` instance.

```
auth = symphony.Auth(symphony_sessionauth_uri, symphony_keymanager_uri, symphony_crt, symphony_key)
```

That happens even when there is an error:

```
        try:
            response = requests.post(self.__session_url__ + 'sessionauth/v1/authenticate',
                                     cert=(self.__crt__, self.__key__), verify=True)
        except requests.exceptions.RequestException as e:
            return e
```

**Comment by openfly** [comment]
That actually is probably worth cleaning up.  Not sure how to handle the signaling for that.  I don't like calling a sys.exit() on a fail.  I'd rather let the user choose how to respond.  So I guess the question is... what should I pass to the user.

**Comment by greenpau** [comment]
> So I guess the question is... what should I pass to the user.

@openfly , throw exception :-)

**Comment by openfly** [comment]
Will fire a 'raise' after logging the exception.  PR is being tested now.

**Comment by openfly** [comment]
Now in 0.2.3
