### ISSUE TITLE
feature: add getting a user by UID

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#56]
Feature request. Add getting a user by UID.

```
    def get_userid_by_uid(self, uid):
        ''' get current user information '''
        req_hook = 'pod/v2/user'
        req_args = '?uid=' + str(uid)
        status_code, response = self.__rest__.GET_query(req_hook, req_args)
        return status_code, response
```

**Comment by openfly** [comment]
Added... though I think I may collapse all the calls to this endpoint into a single method.  Not sure we need or want separate method calls for this sort of thing.  A more generic search method makes more sense to me.

**Comment by openfly** [comment]
In 0.2.4 I will probably refactor at some point.
