### ISSUE TITLE
feature: add set current user's presence

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#57]
Add to `Pod/users.py`:

```
    def set_presence(self, presence):
        req_hook = 'pod/v1/user/presence'
        req_args = {
            "category": presence
        };
        req_args = json.dumps(req_args)
        status_code, response = self.__rest__.POST_query(req_hook, req_args)
        return status_code, response
```

Then, call it:

```
resp_status, resp_data = pod.set_presence('AVAILABLE')
```

**Comment by openfly** [comment]
Hey paul,  don't know if previous message got through.  In Ireland until Friday on vacation.

Big push is to get the swagger codegen to work.  Tricky bit is the PKCS auth bits around keymanager and sessionauth.  I have preliminary approval to work with Yelp's bravado module for the code gen.  But they don't handle PKCS auth methods.  I will have to either decorate ( or worst case fork ) their code base... and try to get a patch in with them.  I have been trying to learn from urllib3 folks how to approach this correctly.

I think the next step here is to go for a 0.2.x release with the swagger code gen in place as this will keep us mapped to releases swagger files with minimal effort, and with specific support as identified in that swagger file.

Not sure all of that makes sense to you, it's a java concept being applied to python as part of an open api initiative.  It's really kind of great... so long as the auth stuff can be figured out.

I'll be glad to sync up with you when I get back... you've been making great suggestions.

Cheers!

**Comment by greenpau** [comment]
> I think the next step here is to go for a 0.2.x release with the swagger code gen in place as this will keep us mapped to releases swagger files with minimal effort, and with specific support as identified in that swagger file.

@openfly , I actually learned the API from the swagger file :-) I think that OpenAPI initiative is great!
Generally, I switched to Go. Currently, I did not find Go support with Symphony. I am not a big fan of C# (Windows) or Java (too heavy). Thus, it would be great to find Go library for Symphony :smile_cat: 

>  I will have to either decorate ( or worst case fork ) their code base... and try to get a patch in with them.

The latter is probably better.

> I'll be glad to sync up with you when I get back... you've been making great suggestions.

Absolutely, give me a buzz. I think you did a great job on Python API, it is very consistent and I was able to quickly recognize programming patterns :+1:

**Comment by openfly** [comment]
I am back.  If you want to hop on a call or something to chat let me know.

**Comment by greenpau** [comment]
@openfly , sure :smile: I pinged you on Linkedin. Will exchange numbers there.

**Comment by openfly** [comment]
In 0.2.4
