### ISSUE TITLE
bug: agent.read_datafeed() is broken

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#58]
The agent's `read_datafeed()` function uses `PKCS_GET_query()` function to get the feed.

In order to read a feed from the agent, a client must have `keyManagerToken` token present.

It manifests itself with `401` status  and the following payload:

```
{'code': 301, 'message': 'No keyManagerToken token'}
```

The `PKCS_GET_query()` headers are missing the `keyManagerToken` header, while in `PKCS_POST_query()` it is present.

A quick fix is to modify the functions in the following way. This way the modification does not impact any of the existing call with `PKCS_GET_query()`:

```
    def PKCS_GET_query(self, req_hook, req_args, req_hdrs={}):
        ''' Generic GET query method '''
        # GET request methods only require sessionTokens
        headers = {'content-type': 'application/json',
                   'sessionToken': self.__session__}
        if req_hdrs:
            if 'keyManagerToken' in req_hdrs:
                headers['keyManagerToken'] = self.__keymngr__;

        # omitted the rest


    def read_datafeed(self, streamid):
        ''' get datafeed '''
        req_hook = 'agent/v1/datafeed/' + str(streamid) + '/read'
        req_args = None
        status_code, response = self.__rest__.PKCS_GET_query(req_hook, req_args, {'keyManagerToken': True})
        response = ast.literal_eval(response)
        return status_code, response
```

**Comment by openfly** [comment]
PKCS is deprecated for these calls now.
And method now uses base binding layer.
