### ISSUE TITLE
feature: update avatar

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#63]
Please add this function:

```
    def set_user_avatar(self, user_id, encoded_image):
        ''' update avatar of a user '''
        req_hook = 'pod/v1/user/' + str(user_id) + '/avatar/update'
        req_args = '{ "image": "'"%s"'" }' % encoded_image
        status_code, response = self.__rest__.POST_query(req_hook, req_args)
        return status_code, response
```

Currently, only administrators can use this function.

Non-admin user would get `{"code":403,"message":"user does not have the proper privilege to perform this action."}`

What is the endpoint for a user to update his or her own image? In browser it is done via POST to `/webcontroller/users/me/avatar`.

**Comment by openfly** [comment]
Added 2 methods... one for get user avatar.  one for update. no clue if they work as I don't have a bot key with admin privs anywhere.

Currently in dev.  Will advise when PR merges.

**Comment by openfly** [comment]
in 0.2.4
